version: '3.3'
services:
#this is here since we can't just pull a built image from the cloud with our libraries
  itech-fhir-libraries:
   image: itech-fhir-libraries
   build:
      context: .
      dockerfile: docker/docker-build/Dockerfile
      
  cs-frontend:
    image: cs-frontend
    build:
      context: ./cs-frontend
      dockerfile: ./Dockerfile.prod    
    depends_on:
      - dataimport.openelis.org
    ports:
      - 443:443
    secrets:
      - source: cert
      - source: key
    
  dataimport.openelis.org:
    image: dataimport-webapp
    build:
      context: ./dataimport-webapp
      dockerfile: docker/docker-build/Dockerfile
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./prod/tomcat/server.xml:/usr/local/tomcat/conf/server.xml
    secrets:
      - source: keystore
      - source: truststore
      
  fhir.openelis.org:
    build: ./hapi-fhir-jpaserver-starter
    restart: always
    environment:
      - JAVA_OPTS= -Dhapi.properties=/run/secrets/hapi.properties
    ports:
      - 8444:8443
    volumes:
      - ./prod/tomcat/server.xml:/usr/local/tomcat/conf/server.xml
    secrets:
      - source: hapi.properties
      - source: keystore
      - source: truststore

  auth.openelis.org:
    image:
      quay.io/keycloak/keycloak:10.0.2
    restart: always
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=
      - DB_PORT=5432
      - DB_DATABASE=consolidated-server
      - DB_SCHEMA=keycloak
      - DB_USER=
      - DB_PASSWORD=
    ports:
      - 8083:8080
      - 8446:8443
    volumes:
      - ./dev/ssl/cs.crt:/etc/x509/https/tls.crt
      - ./dev/ssl/cs.key:/etc/x509/https/tls.key

secrets:
  hapi.properties:
    file: ./prod/properties/hapi.properties
  truststore:
    file: ./prod/ssl/cs.truststore
  keystore:
    file: ./prod/ssl/cs.keystore
  cert:
    file: ./prod/ssl/cs.crt
  key:
    file: ./prod/ssl/cs.key

