version: '3.3'
# lines starting with a #db and #port will be uncommented when setup with a docker database
# lines starting with a #port will be uncommented when setup with a remote database
# lines starting with a #h will be uncommented when setup with a local database
services:
#db    database:
#db        container_name: openelisglobal-database # don't change
#db        image: postgres:9.5
#db        ports:
#db            - "[% db_host_port %]:5432"
#db        restart: always
#db        env_file:
#db            - [% db_env_dir %]database.env
#db        volumes:
#db              # preserves the database between containers
#db            - [% db_data_dir %]:/var/lib/postgresql/data                
#db              # files here will run on install
#db            - [% db_init_dir %]:/docker-entrypoint-initdb.d    
#db              # values must match values in DatabaseBackup.pl
#db            - [% db_backups_dir %]:[% docker_backups_dir %]     
            
    oe.openelisci.org:
        container_name: openelisglobal-webapp # don't change
        image: openelisglobal
        depends_on:
            - datasubscriber.openelisci.org
#db            - database
        ports:
            - "8080:8080"
            - "8443:8443"
        restart: always
        environment:
              # context.xml doesn't seem to be able to pick up environment variables directly, so we are passing them in as CATALINA_OPTS
            - CATALINA_OPTS= -Ddatasource.url=jdbc:postgresql://[% db_host %]:[% db_port %]/clinlims?currentSchema=clinlims -Ddatasource.username=clinlims
        volumes:
            - [% plugins_dir %]:/var/lib/openelis-global/plugins
        secrets:
            - source: keystore
            - source: truststore
            - source: datasource.password
            - source: common.properties
            
    hapi-fhir-jpaserver-starter:
        container_name: hapi-fhir-jpaserver-starter
        image: hapi-fhir-jpaserver-starter
#db        depends_on:
#db            - database
        ports:
            - "8081:8080"
            - "8444:8443"
        restart: always
        environment:
            - JAVA_OPTS= -Dhapi.properties=/run/secrets/hapi.properties
        secrets:
            - source: hapi.properties
            - source: common.properties
            - source: keystore
            - source: truststore
            
    datasubscriber.openelisci.org:
        image: datasubscriber-webapp
        depends_on:
            - hapi-fhir-jpaserver-starter
#db            - database
        ports:
            - 8445:8443
        secrets:
            - source: keystore
            - source: truststore
            - source: common.properties
            
    dataimport.openelisci.org:
        image: dataimport-webapp
#db        depends_on:
#db            - database
        ports:
            - 8446:8443
        secrets:
            - source: keystore
            - source: truststore
            - source: common.properties
            
secrets:
  datasource.password:
    file: [% secrets_dir %]datasource.password  
  common.properties:
    file: [% secrets_dir %]common.properties  
  hapi.properties:
    file: [% secrets_dir %]hapi.properties
  keystore:
    file: /etc/openelis-global/keystore
  truststore:
    file: /etc/openelis-global/truststore